//HintName: linear_parser.registry.debug.cs
/*
```
Token_1 | Name: keyword_var | DependencyInfo: Token_1 | Order: 125 | IsRecursive: False | TreeDepth: [4, 4] | NodeDepth: [0, 0]
Token_2 | Name: keyword_function | DependencyInfo: Token_2 | Order: 126 | IsRecursive: False | TreeDepth: [4, 4] | NodeDepth: [0, 0]
Token_3 | Name: keyword_byte | DependencyInfo: Token_3 | Order: 127 | IsRecursive: False | TreeDepth: [4, 4] | NodeDepth: [0, 0]
Token_4 | Name: keyword_short | DependencyInfo: Token_4 | Order: 128 | IsRecursive: False | TreeDepth: [4, 4] | NodeDepth: [0, 0]
Token_5 | Name: keyword_int | DependencyInfo: Token_5 | Order: 129 | IsRecursive: False | TreeDepth: [4, 4] | NodeDepth: [0, 0]
Token_6 | Name: keyword_float | DependencyInfo: Token_6 | Order: 130 | IsRecursive: False | TreeDepth: [4, 4] | NodeDepth: [0, 0]
Token_7 | Name: open_bracket | DependencyInfo: Token_7 | Order: 110 | IsRecursive: False | TreeDepth: [3, 3] | NodeDepth: [0, 0]
Token_8 | Name: close_bracket | DependencyInfo: Token_8 | Order: 111 | IsRecursive: False | TreeDepth: [3, 3] | NodeDepth: [0, 0]
Token_9 | Name: open_sqbracket | DependencyInfo: Token_9 | Order: 112 | IsRecursive: False | TreeDepth: [3, 3] | NodeDepth: [0, 0]
Token_10 | Name: close_sqbracket | DependencyInfo: Token_10 | Order: 113 | IsRecursive: False | TreeDepth: [3, 3] | NodeDepth: [0, 0]
Token_11 | Name: open_parenthesis | DependencyInfo: Token_11 | Order: 114 | IsRecursive: False | TreeDepth: [3, 3] | NodeDepth: [0, 0]
Token_12 | Name: close_parenthesis | DependencyInfo: Token_12 | Order: 115 | IsRecursive: False | TreeDepth: [3, 3] | NodeDepth: [0, 0]
Token_13 | Name: asterisk | DependencyInfo: Token_13 | Order: 116 | IsRecursive: False | TreeDepth: [3, 3] | NodeDepth: [0, 0]
Token_14 | Name: solidus | DependencyInfo: Token_14 | Order: 117 | IsRecursive: False | TreeDepth: [3, 3] | NodeDepth: [0, 0]
Token_15 | Name: reverse_solidus | DependencyInfo: Token_15 | Order: 118 | IsRecursive: False | TreeDepth: [3, 3] | NodeDepth: [0, 0]
Token_16 | Name: whitespace | DependencyInfo: Token_16 | Order: 119 | IsRecursive: False | TreeDepth: [3, 3] | NodeDepth: [0, 0]
Token_17 | Name: digits | DependencyInfo: Token_17 | Order: 120 | IsRecursive: False | TreeDepth: [3, 3] | NodeDepth: [0, 0]
Token_18 | Name: letters | DependencyInfo: Token_18 | Order: 121 | IsRecursive: False | TreeDepth: [3, 3] | NodeDepth: [0, 0]
Token_19 | Name: newline | DependencyInfo: Token_19 | Order: 122 | IsRecursive: False | TreeDepth: [3, 3] | NodeDepth: [0, 0]
Token_20 | Name: identifier | DependencyInfo: Token_20 | Order: 141 | IsRecursive: False | TreeDepth: [3, 4] | NodeDepth: [0, 0]
Token_21 | Name: typename | DependencyInfo: Token_21 | Order: 167 | IsRecursive: False | TreeDepth: [8, 8] | NodeDepth: [0, 0]
Token_22 | Name: comment | DependencyInfo: Token_22 | Order: 169 | IsRecursive: True | TreeDepth: [3, 9] | NodeDepth: [1, 1]
Token_23 | Name: codeblock | DependencyInfo: Token_23 | Order: 169 | IsRecursive: True | TreeDepth: [4, 9] | NodeDepth: [1, 1]

Consumer_1 | Order: 104 | IsRecursive: False | TreeDepth: [3, 3] | NodeDepth: [0, 0]
Consumer_2 | Order: 105 | IsRecursive: False | TreeDepth: [3, 3] | NodeDepth: [0, 0]
Consumer_3 | Order: 106 | IsRecursive: False | TreeDepth: [3, 3] | NodeDepth: [0, 0]
Consumer_4 | Order: 107 | IsRecursive: False | TreeDepth: [3, 3] | NodeDepth: [0, 0]
Consumer_5 | Order: 108 | IsRecursive: False | TreeDepth: [3, 3] | NodeDepth: [0, 0]
Consumer_6 | Order: 109 | IsRecursive: False | TreeDepth: [3, 3] | NodeDepth: [0, 0]
Consumer_7 | Order: 87 | IsRecursive: False | TreeDepth: [2, 2] | NodeDepth: [0, 0]
Consumer_8 | Order: 88 | IsRecursive: False | TreeDepth: [2, 2] | NodeDepth: [0, 0]
Consumer_9 | Order: 89 | IsRecursive: False | TreeDepth: [2, 2] | NodeDepth: [0, 0]
Consumer_10 | Order: 90 | IsRecursive: False | TreeDepth: [2, 2] | NodeDepth: [0, 0]
Consumer_11 | Order: 91 | IsRecursive: False | TreeDepth: [2, 2] | NodeDepth: [0, 0]
Consumer_12 | Order: 92 | IsRecursive: False | TreeDepth: [2, 2] | NodeDepth: [0, 0]
Consumer_13 | Order: 93 | IsRecursive: False | TreeDepth: [2, 2] | NodeDepth: [0, 0]
Consumer_14 | Order: 94 | IsRecursive: False | TreeDepth: [2, 2] | NodeDepth: [0, 0]
Consumer_15 | Order: 95 | IsRecursive: False | TreeDepth: [2, 2] | NodeDepth: [0, 0]
Consumer_16 | Order: 96 | IsRecursive: False | TreeDepth: [2, 2] | NodeDepth: [0, 0]
Consumer_17 | Order: 97 | IsRecursive: False | TreeDepth: [2, 2] | NodeDepth: [0, 0]
Consumer_18 | Order: 98 | IsRecursive: False | TreeDepth: [2, 2] | NodeDepth: [0, 0]
Consumer_19 | Order: 99 | IsRecursive: False | TreeDepth: [2, 2] | NodeDepth: [0, 0]
Consumer_20 | Order: 123 | IsRecursive: False | TreeDepth: [2, 3] | NodeDepth: [0, 0]
Consumer_21 | Order: 162 | IsRecursive: False | TreeDepth: [7, 7] | NodeDepth: [0, 0]
Consumer_22 | Order: 163 | IsRecursive: False | TreeDepth: [7, 7] | NodeDepth: [0, 0]
Consumer_23 | Order: 164 | IsRecursive: False | TreeDepth: [7, 7] | NodeDepth: [0, 0]
Consumer_24 | Order: 165 | IsRecursive: False | TreeDepth: [7, 7] | NodeDepth: [0, 0]
Consumer_25 | Order: 166 | IsRecursive: False | TreeDepth: [7, 7] | NodeDepth: [0, 0]
Consumer_26 | Order: 124 | IsRecursive: False | TreeDepth: [2, 3] | NodeDepth: [0, 0]
Consumer_27 | Order: 161 | IsRecursive: False | TreeDepth: [6, 6] | NodeDepth: [0, 0]
Consumer_28 | Order: 160 | IsRecursive: False | TreeDepth: [6, 6] | NodeDepth: [0, 0]
Consumer_29 | Order: 159 | IsRecursive: False | TreeDepth: [6, 6] | NodeDepth: [0, 0]

Pattern_1 | Order: 0 | IsRecursive: False | TreeDepth: [0, 0] | NodeDepth: [0, 0]
Pattern_2 | Order: 1 | IsRecursive: False | TreeDepth: [0, 0] | NodeDepth: [0, 0]
Pattern_3 | Order: 2 | IsRecursive: False | TreeDepth: [0, 0] | NodeDepth: [0, 0]
Pattern_4 | Order: 57 | IsRecursive: False | TreeDepth: [1, 1] | NodeDepth: [1, 1]
Pattern_5 | Order: 81 | IsRecursive: False | TreeDepth: [2, 2] | NodeDepth: [2, 2]
Pattern_6 | Order: 3 | IsRecursive: False | TreeDepth: [0, 0] | NodeDepth: [0, 0]
Pattern_7 | Order: 4 | IsRecursive: False | TreeDepth: [0, 0] | NodeDepth: [0, 0]
Pattern_8 | Order: 5 | IsRecursive: False | TreeDepth: [0, 0] | NodeDepth: [0, 0]
Pattern_9 | Order: 6 | IsRecursive: False | TreeDepth: [0, 0] | NodeDepth: [0, 0]
Pattern_10 | Order: 7 | IsRecursive: False | TreeDepth: [0, 0] | NodeDepth: [0, 0]
Pattern_11 | Order: 8 | IsRecursive: False | TreeDepth: [0, 0] | NodeDepth: [0, 0]
Pattern_12 | Order: 9 | IsRecursive: False | TreeDepth: [0, 0] | NodeDepth: [0, 0]
Pattern_13 | Order: 10 | IsRecursive: False | TreeDepth: [0, 0] | NodeDepth: [0, 0]
Pattern_14 | Order: 58 | IsRecursive: False | TreeDepth: [1, 1] | NodeDepth: [1, 1]
Pattern_15 | Order: 82 | IsRecursive: False | TreeDepth: [2, 2] | NodeDepth: [2, 2]
Pattern_16 | Order: 11 | IsRecursive: False | TreeDepth: [0, 0] | NodeDepth: [0, 0]
Pattern_17 | Order: 12 | IsRecursive: False | TreeDepth: [0, 0] | NodeDepth: [0, 0]
Pattern_18 | Order: 13 | IsRecursive: False | TreeDepth: [0, 0] | NodeDepth: [0, 0]
Pattern_19 | Order: 14 | IsRecursive: False | TreeDepth: [0, 0] | NodeDepth: [0, 0]
Pattern_20 | Order: 59 | IsRecursive: False | TreeDepth: [1, 1] | NodeDepth: [1, 1]
Pattern_21 | Order: 83 | IsRecursive: False | TreeDepth: [2, 2] | NodeDepth: [2, 2]
Pattern_22 | Order: 15 | IsRecursive: False | TreeDepth: [0, 0] | NodeDepth: [0, 0]
Pattern_23 | Order: 16 | IsRecursive: False | TreeDepth: [0, 0] | NodeDepth: [0, 0]
Pattern_24 | Order: 17 | IsRecursive: False | TreeDepth: [0, 0] | NodeDepth: [0, 0]
Pattern_25 | Order: 18 | IsRecursive: False | TreeDepth: [0, 0] | NodeDepth: [0, 0]
Pattern_26 | Order: 19 | IsRecursive: False | TreeDepth: [0, 0] | NodeDepth: [0, 0]
Pattern_27 | Order: 60 | IsRecursive: False | TreeDepth: [1, 1] | NodeDepth: [1, 1]
Pattern_28 | Order: 84 | IsRecursive: False | TreeDepth: [2, 2] | NodeDepth: [2, 2]
Pattern_29 | Order: 20 | IsRecursive: False | TreeDepth: [0, 0] | NodeDepth: [0, 0]
Pattern_30 | Order: 21 | IsRecursive: False | TreeDepth: [0, 0] | NodeDepth: [0, 0]
Pattern_31 | Order: 22 | IsRecursive: False | TreeDepth: [0, 0] | NodeDepth: [0, 0]
Pattern_32 | Order: 61 | IsRecursive: False | TreeDepth: [1, 1] | NodeDepth: [1, 1]
Pattern_33 | Order: 85 | IsRecursive: False | TreeDepth: [2, 2] | NodeDepth: [2, 2]
Pattern_34 | Order: 23 | IsRecursive: False | TreeDepth: [0, 0] | NodeDepth: [0, 0]
Pattern_35 | Order: 24 | IsRecursive: False | TreeDepth: [0, 0] | NodeDepth: [0, 0]
Pattern_36 | Order: 25 | IsRecursive: False | TreeDepth: [0, 0] | NodeDepth: [0, 0]
Pattern_37 | Order: 26 | IsRecursive: False | TreeDepth: [0, 0] | NodeDepth: [0, 0]
Pattern_38 | Order: 27 | IsRecursive: False | TreeDepth: [0, 0] | NodeDepth: [0, 0]
Pattern_39 | Order: 62 | IsRecursive: False | TreeDepth: [1, 1] | NodeDepth: [1, 1]
Pattern_40 | Order: 86 | IsRecursive: False | TreeDepth: [2, 2] | NodeDepth: [2, 2]
Pattern_41 | Order: 28 | IsRecursive: False | TreeDepth: [0, 0] | NodeDepth: [0, 0]
Pattern_42 | Order: 63 | IsRecursive: False | TreeDepth: [1, 1] | NodeDepth: [1, 1]
Pattern_43 | Order: 29 | IsRecursive: False | TreeDepth: [0, 0] | NodeDepth: [0, 0]
Pattern_44 | Order: 64 | IsRecursive: False | TreeDepth: [1, 1] | NodeDepth: [1, 1]
Pattern_45 | Order: 30 | IsRecursive: False | TreeDepth: [0, 0] | NodeDepth: [0, 0]
Pattern_46 | Order: 65 | IsRecursive: False | TreeDepth: [1, 1] | NodeDepth: [1, 1]
Pattern_47 | Order: 31 | IsRecursive: False | TreeDepth: [0, 0] | NodeDepth: [0, 0]
Pattern_48 | Order: 66 | IsRecursive: False | TreeDepth: [1, 1] | NodeDepth: [1, 1]
Pattern_49 | Order: 32 | IsRecursive: False | TreeDepth: [0, 0] | NodeDepth: [0, 0]
Pattern_50 | Order: 67 | IsRecursive: False | TreeDepth: [1, 1] | NodeDepth: [1, 1]
Pattern_51 | Order: 33 | IsRecursive: False | TreeDepth: [0, 0] | NodeDepth: [0, 0]
Pattern_52 | Order: 68 | IsRecursive: False | TreeDepth: [1, 1] | NodeDepth: [1, 1]
Pattern_53 | Order: 34 | IsRecursive: False | TreeDepth: [0, 0] | NodeDepth: [0, 0]
Pattern_54 | Order: 69 | IsRecursive: False | TreeDepth: [1, 1] | NodeDepth: [1, 1]
Pattern_55 | Order: 35 | IsRecursive: False | TreeDepth: [0, 0] | NodeDepth: [0, 0]
Pattern_56 | Order: 70 | IsRecursive: False | TreeDepth: [1, 1] | NodeDepth: [1, 1]
Pattern_57 | Order: 36 | IsRecursive: False | TreeDepth: [0, 0] | NodeDepth: [0, 0]
Pattern_58 | Order: 71 | IsRecursive: False | TreeDepth: [1, 1] | NodeDepth: [1, 1]
Pattern_59 | Order: 37 | IsRecursive: False | TreeDepth: [0, 0] | NodeDepth: [0, 0]
Pattern_60 | Order: 38 | IsRecursive: False | TreeDepth: [0, 0] | NodeDepth: [0, 0]
Pattern_61 | Order: 39 | IsRecursive: False | TreeDepth: [0, 0] | NodeDepth: [0, 0]
Pattern_62 | Order: 72 | IsRecursive: False | TreeDepth: [1, 1] | NodeDepth: [1, 1]
Pattern_63 | Order: 40 | IsRecursive: False | TreeDepth: [0, 0] | NodeDepth: [0, 0]
Pattern_64 | Order: 73 | IsRecursive: False | TreeDepth: [1, 1] | NodeDepth: [1, 1]
Pattern_65 | Order: 41 | IsRecursive: False | TreeDepth: [0, 0] | NodeDepth: [0, 0]
Pattern_66 | Order: 42 | IsRecursive: False | TreeDepth: [0, 0] | NodeDepth: [0, 0]
Pattern_67 | Order: 74 | IsRecursive: False | TreeDepth: [1, 1] | NodeDepth: [1, 1]
Pattern_68 | Order: 43 | IsRecursive: False | TreeDepth: [0, 0] | NodeDepth: [0, 0]
Pattern_69 | Order: 44 | IsRecursive: False | TreeDepth: [0, 0] | NodeDepth: [0, 0]
Pattern_70 | Order: 75 | IsRecursive: False | TreeDepth: [1, 1] | NodeDepth: [1, 1]
Pattern_71 | Order: 45 | IsRecursive: False | TreeDepth: [0, 0] | NodeDepth: [0, 0]
Pattern_72 | Order: 46 | IsRecursive: False | TreeDepth: [0, 0] | NodeDepth: [0, 0]
Pattern_73 | Order: 76 | IsRecursive: False | TreeDepth: [1, 1] | NodeDepth: [1, 1]
Pattern_74 | Order: 100 | IsRecursive: False | TreeDepth: [2, 2] | NodeDepth: [2, 2]
Pattern_75 | Order: 47 | IsRecursive: False | TreeDepth: [0, 0] | NodeDepth: [0, 0]
Pattern_76 | Order: 48 | IsRecursive: False | TreeDepth: [0, 0] | NodeDepth: [0, 0]
Pattern_77 | Order: 49 | IsRecursive: False | TreeDepth: [0, 0] | NodeDepth: [0, 0]
Pattern_78 | Order: 50 | IsRecursive: False | TreeDepth: [0, 0] | NodeDepth: [0, 0]
Pattern_79 | Order: 51 | IsRecursive: False | TreeDepth: [0, 0] | NodeDepth: [0, 0]
Pattern_80 | Order: 77 | IsRecursive: False | TreeDepth: [1, 1] | NodeDepth: [1, 1]
Pattern_81 | Order: 101 | IsRecursive: False | TreeDepth: [2, 2] | NodeDepth: [2, 2]
Pattern_82 | Order: 142 | IsRecursive: False | TreeDepth: [5, 5] | NodeDepth: [0, 0]
Pattern_83 | Order: 154 | IsRecursive: False | TreeDepth: [6, 6] | NodeDepth: [1, 1]
Pattern_84 | Order: 143 | IsRecursive: False | TreeDepth: [5, 5] | NodeDepth: [0, 0]
Pattern_85 | Order: 155 | IsRecursive: False | TreeDepth: [6, 6] | NodeDepth: [1, 1]
Pattern_86 | Order: 144 | IsRecursive: False | TreeDepth: [5, 5] | NodeDepth: [0, 0]
Pattern_87 | Order: 156 | IsRecursive: False | TreeDepth: [6, 6] | NodeDepth: [1, 1]
Pattern_88 | Order: 145 | IsRecursive: False | TreeDepth: [5, 5] | NodeDepth: [0, 0]
Pattern_89 | Order: 157 | IsRecursive: False | TreeDepth: [6, 6] | NodeDepth: [1, 1]
Pattern_90 | Order: 146 | IsRecursive: False | TreeDepth: [5, 5] | NodeDepth: [0, 0]
Pattern_91 | Order: 158 | IsRecursive: False | TreeDepth: [6, 6] | NodeDepth: [1, 1]
Pattern_92 | Order: 52 | IsRecursive: False | TreeDepth: [0, 0] | NodeDepth: [0, 0]
Pattern_93 | Order: 53 | IsRecursive: False | TreeDepth: [0, 0] | NodeDepth: [0, 0]
Pattern_94 | Order: 78 | IsRecursive: False | TreeDepth: [1, 1] | NodeDepth: [1, 1]
Pattern_95 | Order: 102 | IsRecursive: False | TreeDepth: [2, 2] | NodeDepth: [2, 2]
Pattern_96 | Order: 54 | IsRecursive: False | TreeDepth: [0, 0] | NodeDepth: [0, 0]
Pattern_97 | Order: 55 | IsRecursive: False | TreeDepth: [0, 0] | NodeDepth: [0, 0]
Pattern_98 | Order: 79 | IsRecursive: False | TreeDepth: [1, 1] | NodeDepth: [1, 1]
Pattern_99 | Order: 103 | IsRecursive: False | TreeDepth: [2, 2] | NodeDepth: [2, 2]
Pattern_100 | Order: 56 | IsRecursive: False | TreeDepth: [0, 0] | NodeDepth: [0, 0]
Pattern_101 | Order: 80 | IsRecursive: False | TreeDepth: [1, 1] | NodeDepth: [1, 1]
Pattern_102 | Order: 135 | IsRecursive: False | TreeDepth: [4, 4] | NodeDepth: [0, 0]
Pattern_103 | Order: 136 | IsRecursive: False | TreeDepth: [4, 4] | NodeDepth: [0, 0]
Pattern_104 | Order: 149 | IsRecursive: False | TreeDepth: [5, 5] | NodeDepth: [1, 1]
Pattern_105 | Order: 140 | IsRecursive: False | TreeDepth: [4, 4] | NodeDepth: [0, 0]
Pattern_106 | Order: 153 | IsRecursive: False | TreeDepth: [5, 5] | NodeDepth: [1, 1]
Pattern_107 | Order: 137 | IsRecursive: False | TreeDepth: [4, 4] | NodeDepth: [0, 0]
Pattern_108 | Order: 133 | IsRecursive: False | TreeDepth: [4, 4] | NodeDepth: [0, 0]
Pattern_109 | Order: 150 | IsRecursive: False | TreeDepth: [5, 5] | NodeDepth: [1, 1]
Pattern_110 | Order: 134 | IsRecursive: False | TreeDepth: [4, 4] | NodeDepth: [0, 0]
Pattern_111 | Order: 138 | IsRecursive: False | TreeDepth: [4, 4] | NodeDepth: [0, 0]
Pattern_112 | Order: 151 | IsRecursive: False | TreeDepth: [5, 5] | NodeDepth: [1, 1]
Pattern_113 | Order: 139 | IsRecursive: False | TreeDepth: [4, 4] | NodeDepth: [0, 0]
Pattern_114 | Order: 152 | IsRecursive: False | TreeDepth: [5, 5] | NodeDepth: [1, 1]
Pattern_115 | Order: 131 | IsRecursive: False | TreeDepth: [4, 4] | NodeDepth: [0, 0]
Pattern_116 | Order: 147 | IsRecursive: False | TreeDepth: [5, 5] | NodeDepth: [1, 1]
Pattern_117 | Order: 132 | IsRecursive: False | TreeDepth: [4, 4] | NodeDepth: [0, 0]
Pattern_118 | Order: 148 | IsRecursive: False | TreeDepth: [5, 5] | NodeDepth: [1, 1]
```
*/
