using System;
using System.Collections.Generic;

namespace MetaParser.Generation;

/// <summary>
/// Builds a complete generated source file with proper structure.
/// </summary>
internal sealed class GeneratedFileBuilder
{
    private readonly string _namespace;
    private readonly List<string> _usings;
    private readonly CodeBuilder _code;
    private bool _nullableEnabled;
    private string? _fileName;

    public GeneratedFileBuilder(string namespaceName)
    {
        _namespace = namespaceName;
        _usings = new List<string>();
        _code = new CodeBuilder();
        _nullableEnabled = true;
    }

    /// <summary>
    /// Sets the file name hint for the generated file.
    /// </summary>
    public GeneratedFileBuilder WithFileName(string fileName)
    {
        _fileName = fileName;
        return this;
    }

    /// <summary>
    /// Gets the file name hint.
    /// </summary>
    public string FileName => _fileName ?? "Generated.g.cs";

    /// <summary>
    /// Adds a using directive.
    /// </summary>
    public GeneratedFileBuilder AddUsing(string usingNamespace)
    {
        if (!_usings.Contains(usingNamespace))
        {
            _usings.Add(usingNamespace);
        }
        return this;
    }

    /// <summary>
    /// Adds multiple using directives.
    /// </summary>
    public GeneratedFileBuilder AddUsings(params string[] namespaces)
    {
        foreach (var ns in namespaces)
        {
            AddUsing(ns);
        }
        return this;
    }

    /// <summary>
    /// Sets whether nullable reference types are enabled.
    /// </summary>
    public GeneratedFileBuilder WithNullable(bool enabled)
    {
        _nullableEnabled = enabled;
        return this;
    }

    /// <summary>
    /// Gets the code builder for adding content.
    /// </summary>
    public CodeBuilder Code => _code;

    /// <summary>
    /// Builds the complete source file.
    /// </summary>
    public string Build()
    {
        var result = new CodeBuilder();

        // File header
        result.AppendLine("// <auto-generated/>");
        result.AppendLine("// This file was generated by MetaParser. Do not edit manually.");
        result.AppendLine();

        // Nullable directive
        if (_nullableEnabled)
        {
            result.AppendLine("#nullable enable");
            result.AppendLine();
        }

        // Using directives
        _usings.Sort(UsingComparer.Instance);
        foreach (var u in _usings)
        {
            result.AppendLine($"using {u};");
        }
        if (_usings.Count > 0)
        {
            result.AppendLine();
        }

        // Namespace
        result.AppendLine($"namespace {_namespace};");
        result.AppendLine();

        // Content
        result.Append(_code.ToString());

        return result.ToString();
    }

    /// <summary>
    /// Comparer that sorts System namespaces first.
    /// </summary>
    private sealed class UsingComparer : IComparer<string>
    {
        public static readonly UsingComparer Instance = new();

        public int Compare(string? x, string? y)
        {
            if (x == null || y == null) return 0;

            bool xIsSystem = x.StartsWith("System", StringComparison.Ordinal);
            bool yIsSystem = y.StartsWith("System", StringComparison.Ordinal);

            if (xIsSystem && !yIsSystem) return -1;
            if (!xIsSystem && yIsSystem) return 1;

            return string.Compare(x, y, StringComparison.Ordinal);
        }
    }
}

/// <summary>
/// Extension methods for SourceProductionContext.
/// </summary>
internal static class GeneratedFileExtensions
{
    /// <summary>
    /// Adds a generated file to the compilation.
    /// </summary>
    public static void AddSource(
        this Microsoft.CodeAnalysis.SourceProductionContext context,
        GeneratedFileBuilder builder)
    {
        context.AddSource(builder.FileName, builder.Build());
    }
}
