//HintName: recursive_parser.registry.debug.cs
/*
```
Token_1 | Name: solidus | DependencyInfo: Token_1 | Order: 57 | IsRecursive: False | TreeDepth: [3, 3] | NodeDepth: [0, 0]
Token_2 | Name: colon | DependencyInfo: Token_2 | Order: 58 | IsRecursive: False | TreeDepth: [3, 3] | NodeDepth: [0, 0]
Token_3 | Name: semicolon | DependencyInfo: Token_3 | Order: 59 | IsRecursive: False | TreeDepth: [3, 3] | NodeDepth: [0, 0]
Token_4 | Name: open_bracket | DependencyInfo: Token_4 | Order: 60 | IsRecursive: False | TreeDepth: [3, 3] | NodeDepth: [0, 0]
Token_5 | Name: close_bracket | DependencyInfo: Token_5 | Order: 61 | IsRecursive: False | TreeDepth: [3, 3] | NodeDepth: [0, 0]
Token_6 | Name: open_sqbracket | DependencyInfo: Token_6 | Order: 62 | IsRecursive: False | TreeDepth: [3, 3] | NodeDepth: [0, 0]
Token_7 | Name: close_sqbracket | DependencyInfo: Token_7 | Order: 63 | IsRecursive: False | TreeDepth: [3, 3] | NodeDepth: [0, 0]
Token_8 | Name: open_parenthesis | DependencyInfo: Token_8 | Order: 64 | IsRecursive: False | TreeDepth: [3, 3] | NodeDepth: [0, 0]
Token_9 | Name: close_parenthesis | DependencyInfo: Token_9 | Order: 65 | IsRecursive: False | TreeDepth: [3, 3] | NodeDepth: [0, 0]
Token_10 | Name: whitespace | DependencyInfo: Token_10 | Order: 66 | IsRecursive: False | TreeDepth: [3, 3] | NodeDepth: [0, 0]
Token_11 | Name: newline | DependencyInfo: Token_11 | Order: 67 | IsRecursive: False | TreeDepth: [3, 3] | NodeDepth: [0, 0]
Token_12 | Name: identifier | DependencyInfo: Token_12 | Order: 77 | IsRecursive: False | TreeDepth: [3, 4] | NodeDepth: [0, 0]
Token_13 | Name: comment | DependencyInfo: Token_13 | Order: 88 | IsRecursive: True | TreeDepth: [3, 7] | NodeDepth: [1, 1]
Token_14 | Name: declaration | DependencyInfo: Token_14 | Order: 88 | IsRecursive: True | TreeDepth: [4, 8] | NodeDepth: [1, 1]
Token_15 | Name: codeblock | DependencyInfo: Token_15 | Order: 88 | IsRecursive: True | TreeDepth: [0, 0] | NodeDepth: [0, 0]

Consumer_1 | Order: 42 | IsRecursive: False | TreeDepth: [2, 2] | NodeDepth: [0, 0]
Consumer_2 | Order: 43 | IsRecursive: False | TreeDepth: [2, 2] | NodeDepth: [0, 0]
Consumer_3 | Order: 44 | IsRecursive: False | TreeDepth: [2, 2] | NodeDepth: [0, 0]
Consumer_4 | Order: 45 | IsRecursive: False | TreeDepth: [2, 2] | NodeDepth: [0, 0]
Consumer_5 | Order: 46 | IsRecursive: False | TreeDepth: [2, 2] | NodeDepth: [0, 0]
Consumer_6 | Order: 47 | IsRecursive: False | TreeDepth: [2, 2] | NodeDepth: [0, 0]
Consumer_7 | Order: 48 | IsRecursive: False | TreeDepth: [2, 2] | NodeDepth: [0, 0]
Consumer_8 | Order: 49 | IsRecursive: False | TreeDepth: [2, 2] | NodeDepth: [0, 0]
Consumer_9 | Order: 50 | IsRecursive: False | TreeDepth: [2, 2] | NodeDepth: [0, 0]
Consumer_10 | Order: 51 | IsRecursive: False | TreeDepth: [2, 2] | NodeDepth: [0, 0]
Consumer_11 | Order: 52 | IsRecursive: False | TreeDepth: [2, 2] | NodeDepth: [0, 0]
Consumer_12 | Order: 68 | IsRecursive: False | TreeDepth: [2, 3] | NodeDepth: [0, 0]
Consumer_13 | Order: 69 | IsRecursive: False | TreeDepth: [2, 3] | NodeDepth: [0, 0]
Consumer_14 | Order: 84 | IsRecursive: False | TreeDepth: [6, 6] | NodeDepth: [0, 0]
Consumer_15 | Order: 86 | IsRecursive: False | TreeDepth: [6, 7] | NodeDepth: [0, 0]
Consumer_16 | Order: 88 | IsRecursive: True | TreeDepth: [6, 6] | NodeDepth: [0, 0]

Pattern_1 | Order: 0 | IsRecursive: False | TreeDepth: [0, 0] | NodeDepth: [0, 0]
Pattern_2 | Order: 26 | IsRecursive: False | TreeDepth: [1, 1] | NodeDepth: [1, 1]
Pattern_3 | Order: 1 | IsRecursive: False | TreeDepth: [0, 0] | NodeDepth: [0, 0]
Pattern_4 | Order: 27 | IsRecursive: False | TreeDepth: [1, 1] | NodeDepth: [1, 1]
Pattern_5 | Order: 2 | IsRecursive: False | TreeDepth: [0, 0] | NodeDepth: [0, 0]
Pattern_6 | Order: 28 | IsRecursive: False | TreeDepth: [1, 1] | NodeDepth: [1, 1]
Pattern_7 | Order: 3 | IsRecursive: False | TreeDepth: [0, 0] | NodeDepth: [0, 0]
Pattern_8 | Order: 29 | IsRecursive: False | TreeDepth: [1, 1] | NodeDepth: [1, 1]
Pattern_9 | Order: 4 | IsRecursive: False | TreeDepth: [0, 0] | NodeDepth: [0, 0]
Pattern_10 | Order: 30 | IsRecursive: False | TreeDepth: [1, 1] | NodeDepth: [1, 1]
Pattern_11 | Order: 5 | IsRecursive: False | TreeDepth: [0, 0] | NodeDepth: [0, 0]
Pattern_12 | Order: 31 | IsRecursive: False | TreeDepth: [1, 1] | NodeDepth: [1, 1]
Pattern_13 | Order: 6 | IsRecursive: False | TreeDepth: [0, 0] | NodeDepth: [0, 0]
Pattern_14 | Order: 32 | IsRecursive: False | TreeDepth: [1, 1] | NodeDepth: [1, 1]
Pattern_15 | Order: 7 | IsRecursive: False | TreeDepth: [0, 0] | NodeDepth: [0, 0]
Pattern_16 | Order: 33 | IsRecursive: False | TreeDepth: [1, 1] | NodeDepth: [1, 1]
Pattern_17 | Order: 8 | IsRecursive: False | TreeDepth: [0, 0] | NodeDepth: [0, 0]
Pattern_18 | Order: 34 | IsRecursive: False | TreeDepth: [1, 1] | NodeDepth: [1, 1]
Pattern_19 | Order: 9 | IsRecursive: False | TreeDepth: [0, 0] | NodeDepth: [0, 0]
Pattern_20 | Order: 10 | IsRecursive: False | TreeDepth: [0, 0] | NodeDepth: [0, 0]
Pattern_21 | Order: 11 | IsRecursive: False | TreeDepth: [0, 0] | NodeDepth: [0, 0]
Pattern_22 | Order: 35 | IsRecursive: False | TreeDepth: [1, 1] | NodeDepth: [1, 1]
Pattern_23 | Order: 12 | IsRecursive: False | TreeDepth: [0, 0] | NodeDepth: [0, 0]
Pattern_24 | Order: 13 | IsRecursive: False | TreeDepth: [0, 0] | NodeDepth: [0, 0]
Pattern_25 | Order: 36 | IsRecursive: False | TreeDepth: [1, 1] | NodeDepth: [1, 1]
Pattern_26 | Order: 14 | IsRecursive: False | TreeDepth: [0, 0] | NodeDepth: [0, 0]
Pattern_27 | Order: 15 | IsRecursive: False | TreeDepth: [0, 0] | NodeDepth: [0, 0]
Pattern_28 | Order: 37 | IsRecursive: False | TreeDepth: [1, 1] | NodeDepth: [1, 1]
Pattern_29 | Order: 53 | IsRecursive: False | TreeDepth: [2, 2] | NodeDepth: [2, 2]
Pattern_30 | Order: 16 | IsRecursive: False | TreeDepth: [0, 0] | NodeDepth: [0, 0]
Pattern_31 | Order: 17 | IsRecursive: False | TreeDepth: [0, 0] | NodeDepth: [0, 0]
Pattern_32 | Order: 18 | IsRecursive: False | TreeDepth: [0, 0] | NodeDepth: [0, 0]
Pattern_33 | Order: 19 | IsRecursive: False | TreeDepth: [0, 0] | NodeDepth: [0, 0]
Pattern_34 | Order: 20 | IsRecursive: False | TreeDepth: [0, 0] | NodeDepth: [0, 0]
Pattern_35 | Order: 38 | IsRecursive: False | TreeDepth: [1, 1] | NodeDepth: [1, 1]
Pattern_36 | Order: 54 | IsRecursive: False | TreeDepth: [2, 2] | NodeDepth: [2, 2]
Pattern_37 | Order: 21 | IsRecursive: False | TreeDepth: [0, 0] | NodeDepth: [0, 0]
Pattern_38 | Order: 22 | IsRecursive: False | TreeDepth: [0, 0] | NodeDepth: [0, 0]
Pattern_39 | Order: 39 | IsRecursive: False | TreeDepth: [1, 1] | NodeDepth: [1, 1]
Pattern_40 | Order: 55 | IsRecursive: False | TreeDepth: [2, 2] | NodeDepth: [2, 2]
Pattern_41 | Order: 23 | IsRecursive: False | TreeDepth: [0, 0] | NodeDepth: [0, 0]
Pattern_42 | Order: 24 | IsRecursive: False | TreeDepth: [0, 0] | NodeDepth: [0, 0]
Pattern_43 | Order: 40 | IsRecursive: False | TreeDepth: [1, 1] | NodeDepth: [1, 1]
Pattern_44 | Order: 56 | IsRecursive: False | TreeDepth: [2, 2] | NodeDepth: [2, 2]
Pattern_45 | Order: 25 | IsRecursive: False | TreeDepth: [0, 0] | NodeDepth: [0, 0]
Pattern_46 | Order: 41 | IsRecursive: False | TreeDepth: [1, 1] | NodeDepth: [1, 1]
Pattern_47 | Order: 70 | IsRecursive: False | TreeDepth: [4, 4] | NodeDepth: [0, 0]
Pattern_48 | Order: 71 | IsRecursive: False | TreeDepth: [4, 4] | NodeDepth: [0, 0]
Pattern_49 | Order: 78 | IsRecursive: False | TreeDepth: [5, 5] | NodeDepth: [1, 1]
Pattern_50 | Order: 76 | IsRecursive: False | TreeDepth: [4, 4] | NodeDepth: [0, 0]
Pattern_51 | Order: 82 | IsRecursive: False | TreeDepth: [5, 5] | NodeDepth: [1, 1]
Pattern_52 | Order: 83 | IsRecursive: False | TreeDepth: [4, 5] | NodeDepth: [0, 0]
Pattern_53 | Order: 72 | IsRecursive: False | TreeDepth: [4, 4] | NodeDepth: [0, 0]
Pattern_54 | Order: 85 | IsRecursive: False | TreeDepth: [5, 6] | NodeDepth: [1, 1]
Pattern_55 | Order: 73 | IsRecursive: False | TreeDepth: [4, 4] | NodeDepth: [0, 0]
Pattern_56 | Order: 79 | IsRecursive: False | TreeDepth: [5, 5] | NodeDepth: [1, 1]
Pattern_57 | Order: 74 | IsRecursive: False | TreeDepth: [4, 4] | NodeDepth: [0, 0]
Pattern_58 | Order: 80 | IsRecursive: False | TreeDepth: [5, 5] | NodeDepth: [1, 1]
Pattern_59 | Order: 88 | IsRecursive: True | TreeDepth: [0, 0] | NodeDepth: [0, 0]
Pattern_60 | Order: 88 | IsRecursive: True | TreeDepth: [0, 0] | NodeDepth: [0, 0]
Pattern_61 | Order: 75 | IsRecursive: False | TreeDepth: [4, 4] | NodeDepth: [0, 0]
Pattern_62 | Order: 81 | IsRecursive: False | TreeDepth: [5, 5] | NodeDepth: [1, 1]
```
*/
