using MetaParser.Generation;
using Xunit;

namespace UnitTests.Generation;

/// <summary>
/// Tests for GeneratedFileBuilder.
/// </summary>
public class GeneratedFileBuilderTests
{
    [Fact]
    public void Build_IncludesAutoGeneratedHeader()
    {
        var builder = new GeneratedFileBuilder("TestNamespace");
        
        var result = builder.Build();
        
        Assert.Contains("// <auto-generated/>", result);
        Assert.Contains("// This file was generated by MetaParser", result);
    }

    [Fact]
    public void Build_IncludesNullableDirective()
    {
        var builder = new GeneratedFileBuilder("TestNamespace");
        
        var result = builder.Build();
        
        Assert.Contains("#nullable enable", result);
    }

    [Fact]
    public void WithNullable_False_OmitsDirective()
    {
        var builder = new GeneratedFileBuilder("TestNamespace")
            .WithNullable(false);
        
        var result = builder.Build();
        
        Assert.DoesNotContain("#nullable", result);
    }

    [Fact]
    public void Build_IncludesFileScopedNamespace()
    {
        var builder = new GeneratedFileBuilder("MyApp.Syntax");
        
        var result = builder.Build();
        
        Assert.Contains("namespace MyApp.Syntax;", result);
    }

    [Fact]
    public void AddUsing_IncludesUsingDirective()
    {
        var builder = new GeneratedFileBuilder("TestNamespace")
            .AddUsing("System.Text");
        
        var result = builder.Build();
        
        Assert.Contains("using System.Text;", result);
    }

    [Fact]
    public void AddUsings_SortsSystemFirst()
    {
        var builder = new GeneratedFileBuilder("TestNamespace")
            .AddUsings("MyApp.Utils", "System.Text", "System");
        
        var result = builder.Build();
        
        int systemIndex = result.IndexOf("using System;");
        int systemTextIndex = result.IndexOf("using System.Text;");
        int myAppIndex = result.IndexOf("using MyApp.Utils;");
        
        Assert.True(systemIndex < systemTextIndex);
        Assert.True(systemTextIndex < myAppIndex);
    }

    [Fact]
    public void AddUsing_DeduplicatesNamespaces()
    {
        var builder = new GeneratedFileBuilder("TestNamespace")
            .AddUsing("System")
            .AddUsing("System")
            .AddUsing("System");
        
        var result = builder.Build();
        
        // Count occurrences of "using System;"
        int count = 0;
        int index = 0;
        while ((index = result.IndexOf("using System;", index)) != -1)
        {
            count++;
            index++;
        }
        
        Assert.Equal(1, count);
    }

    [Fact]
    public void Code_AllowsAddingContent()
    {
        var builder = new GeneratedFileBuilder("TestNamespace");
        builder.Code.AppendLine("public class Foo { }");
        
        var result = builder.Build();
        
        Assert.Contains("public class Foo { }", result);
    }

    [Fact]
    public void WithFileName_SetsFileName()
    {
        var builder = new GeneratedFileBuilder("TestNamespace")
            .WithFileName("MyClass.g.cs");
        
        Assert.Equal("MyClass.g.cs", builder.FileName);
    }

    [Fact]
    public void FileName_DefaultsToGenerated()
    {
        var builder = new GeneratedFileBuilder("TestNamespace");
        
        Assert.Equal("Generated.g.cs", builder.FileName);
    }
}
