//HintName: MetaParser.MetaParser.parser.enum.g.cs
namespace UnitTestParser;
public enum ETokenType : byte
{
    Unknown = (byte) 0,
    Whitespace = (byte) 0,
    Newline = (byte) 1,
    Keyword_Var = (byte) 2,
    Keyword_Vars = (byte) 3,
    Keyword_Function = (byte) 4,
    Keyword_Byte = (byte) 5,
    Keyword_Short = (byte) 6,
    Keyword_Int = (byte) 7,
    Keyword_Uint = (byte) 8,
    Keyword_Float = (byte) 9,
    Char_Open_Bracket = (byte) 10,
    Char_Close_Bracket = (byte) 11,
    Char_Open_Sqbracket = (byte) 12,
    Char_Close_Sqbracket = (byte) 13,
    Char_Open_Parenthesis = (byte) 14,
    Char_Close_Parenthesis = (byte) 15,
    Char_Colon = (byte) 16,
    Char_Semicolon = (byte) 17,
    Char_Asterisk = (byte) 18,
    Char_At_Symbol = (byte) 19,
    Char_Single_Quote = (byte) 20,
    Char_Double_Quote = (byte) 21,
    Char_Solidus = (byte) 22,
    Char_Reverse_Solidus = (byte) 23,
    Digits = (byte) 24,
    Identifier = (byte) 25,
    Comment = (byte) 26,
    Typename = (byte) 27,
    String_Single_Line = (byte) 28,
    String_Multi_Line = (byte) 29,
    Comment = (byte) 30,
    Declaration = (byte) 31,
    Codeblock = (byte) 32,
    Program = (byte) 33,
}
