//HintName: MetaParser.MetaParser.parser.enum.g.cs
namespace UnitTestParser;
public enum ETokenType : byte
{
    Unknown = (byte) 0,
    Whitespace,
    Newline,
    Keyword_Var,
    Keyword_Vars,
    Keyword_Function,
    Keyword_Byte,
    Keyword_Short,
    Keyword_Int,
    Keyword_Uint,
    Keyword_Float,
    Char_Open_Bracket,
    Char_Close_Bracket,
    Char_Open_Sqbracket,
    Char_Close_Sqbracket,
    Char_Open_Parenthesis,
    Char_Close_Parenthesis,
    Char_Colon,
    Char_Semicolon,
    Char_Asterisk,
    Char_At_Symbol,
    Char_Single_Quote,
    Char_Double_Quote,
    Char_Solidus,
    Char_Reverse_Solidus,
    Digits,
    Identifier,
    Comment,
    Typename,
    String_Single_Line,
    String_Multi_Line,
    Declaration,
    Codeblock,
    Program,
}
