//HintName: MetaParser.MetaParser.parser.enum.g.cs
namespace UnitTestParser;
public enum ETokenType : byte
{
    Unknown = (byte) 0,
    Keyword_Var = (byte) 0,
    Keyword_Function = (byte) 1,
    Keyword_Byte = (byte) 2,
    Keyword_Short = (byte) 3,
    Keyword_Int = (byte) 4,
    Keyword_Float = (byte) 5,
    Char_Open_Bracket = (byte) 6,
    Char_Close_Bracket = (byte) 7,
    Char_Open_Sqbracket = (byte) 8,
    Char_Close_Sqbracket = (byte) 9,
    Char_Open_Parenthesis = (byte) 10,
    Char_Close_Parenthesis = (byte) 11,
    Char_Colon = (byte) 12,
    Char_Semicolon = (byte) 13,
    Char_Asterisk = (byte) 14,
    Char_Solidus = (byte) 15,
    Char_Reverse_Solidus = (byte) 16,
    Whitespace = (byte) 17,
    Digits = (byte) 18,
    Newline = (byte) 19,
    Identifier = (byte) 20,
    Comment = (byte) 21,
    Comment = (byte) 22,
    Typename = (byte) 23,
    Declaration = (byte) 24,
    Codeblock = (byte) 25,
    Program = (byte) 26,
}
